import {
  Activity,
  ArrowUpRight,
  BarChart3,
  BookOpen,
  Brain,
  BrainCircuit,
  ChartNoAxesCombined,
  CheckCheck,
  ChevronDown,
  ChevronRight,
  Database,
  FileText,
  FolderOpen,
  Github,
  Headphones,
  HelpCircle,
  LayoutDashboard,
  LogOut,
  Megaphone,
  MessageSquare,
  MessagesSquare,
  Paintbrush,
  Phone,
  Plug,
  Radio,
  Route,
  Settings,
  Shield,
  Table2,
  User,
  UserCog,
  UserRound,
  Users,
  UsersRound,
  Workflow,
} from 'lucide-angular';

/**
 * Lucide icon registry for navigation and chrome.
 *
 * Components that render dynamic icons by string key import this map and
 * resolve `iconKey -> LucideIconData`. Keep keys kebab-case so the data files
 * (e.g. nav-data.ts) read like configuration, not code.
 */
export const NAV_ICONS = {
  activity: Activity,
  'arrow-up-right': ArrowUpRight,
  'bar-chart-3': BarChart3,
  'book-open': BookOpen,
  brain: Brain,
  'brain-circuit': BrainCircuit,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'check-check': CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  database: Database,
  'file-text': FileText,
  'folder-open': FolderOpen,
  github: Github,
  headphones: Headphones,
  'help-circle': HelpCircle,
  'layout-dashboard': LayoutDashboard,
  'log-out': LogOut,
  megaphone: Megaphone,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  paintbrush: Paintbrush,
  phone: Phone,
  plug: Plug,
  radio: Radio,
  route: Route,
  settings: Settings,
  shield: Shield,
  'table-2': Table2,
  user: User,
  'user-cog': UserCog,
  'user-round': UserRound,
  users: Users,
  'users-round': UsersRound,
  workflow: Workflow,
} as const;

export type NavIconKey = keyof typeof NAV_ICONS;
