export interface Group {
  id: number;
  code: string;
  name: string;
  phone: string;
  agents: number;
  priority: "Baja" | "Media" | "Alta" | "Máxima";
  typification: boolean;
  channels: ("phone" | "chat" | "email")[];
  strategy: string;
  chatStrategy?: string;
  capacityType?: "fixed" | "variable";
  capacityValue?: string;
  assignedAgents: string[];
  labels?: number[];
  templates?: number[];
  levels?: string[][];
  subStrategy?: string;
  ringAllAgents?: number;
  /** Servicios VUI asociados (solo lectura, se configuran desde el VUI) */
  services?: string[];
  /** Agendas asignadas al grupo (IDs de availableSchedules) */
  schedules?: number[];
  /** Draft flag — set on duplicated entities until user saves from edit form (DD#294) */
  isDraft?: boolean;
}

export const groupsData: Group[] = [
  {
    id: 1,
    code: "20001",
    name: "ACD Demo C2CB",
    phone: "918371548",
    agents: 11,
    priority: "Media",
    typification: false,
    channels: ["phone"],
    strategy: "Balanceada",
    capacityType: "fixed",
    capacityValue: "5",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez"],
    labels: [1, 5],
    templates: [1, 3, 6],
    services: ["Atención general", "Soporte técnico"],
    schedules: [1, 2],
  },
  {
    id: 2,
    code: "20002",
    name: "ACD demo cuscare",
    phone: "918371548",
    agents: 11,
    priority: "Baja",
    typification: false,
    channels: ["phone", "email"],
    strategy: "Balanceada",
    capacityType: "fixed",
    capacityValue: "10",
    assignedAgents: ["Mario Perez", "Marta Recio", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis", "Rafael", "Angel personal", "Agente AED 1", "Agente AED 2", "Agente demo", "Miguel Palacios 2"],
    services: ["Atención general"],
  },
  {
    id: 3,
    code: "20003",
    name: "ACD outbound",
    phone: "918371548",
    agents: 12,
    priority: "Baja",
    typification: true,
    channels: ["phone"],
    strategy: "Balanceada",
    capacityType: "variable",
    capacityValue: "3",
    assignedAgents: ["Marta Recio", "Oscar Bello", "Agente AED 1", "Agente AED 2", "Jose Barcala", "Mario Perez", "Miguel Palacios", "Miguel Palacios 3", "Oscar Fernandez", "Oscar Quobis", "Rafael", "Angel personal"],
    services: ["Campañas salientes"],
    schedules: [1],
  },
  {
    id: 4,
    code: "20004",
    name: "Campaigns",
    phone: "917945449",
    agents: 11,
    priority: "Baja",
    typification: false,
    channels: ["phone"],
    strategy: "Lineal",
    assignedAgents: ["Agente AED 1", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Oscar Bello", "Oscar Fernandez", "Rafael", "Miguel Palacios 2"],
    services: ["Campañas salientes", "Telemarketing VUI"],
  },
  {
    id: 5,
    code: "20005",
    name: "Exclusivo",
    phone: "918371548",
    agents: 12,
    priority: "Máxima",
    typification: false,
    channels: ["phone"],
    strategy: "Agente exclusivo",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis"],
    services: ["VIP Empresas"],
    schedules: [6],
  },
  {
    id: 6,
    code: "20006",
    name: "Grupo de prueba 1",
    phone: "917945449",
    agents: 4,
    priority: "Baja",
    typification: false,
    channels: ["phone"],
    strategy: "Balanceada",
    assignedAgents: ["Agente AED 1", "Agente demo", "Oscar Bello", "Rafael"],
  },
  {
    id: 7,
    code: "20007",
    name: "Grupo de prueba 2",
    phone: "917945449",
    agents: 4,
    priority: "Baja",
    typification: false,
    channels: ["phone"],
    strategy: "Ring All",
    ringAllAgents: 3,
    assignedAgents: ["Mario Perez", "Marta Recio", "Jose Barcala", "Angel personal"],
  },
  {
    id: 8,
    code: "20008",
    name: "Grupo demo",
    phone: "917945449",
    agents: 9,
    priority: "Baja",
    typification: true,
    channels: ["phone"],
    strategy: "Balanceada",
    assignedAgents: ["Agente Jose", "Jose Barcala", "Miguel Palacios", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis", "Rafael", "Angel personal", "Miguel Palacios 2"],
    services: ["Demo interno"],
  },
  {
    id: 9,
    code: "20009",
    name: "Grupo pedidos",
    phone: "917945449",
    agents: 12,
    priority: "Baja",
    typification: true,
    channels: ["phone"],
    strategy: "Niveles",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis"],
    levels: [
      ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala"],
      ["Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3"],
    ],
    subStrategy: "Balanceada",
    services: ["Pedidos online", "Seguimiento envíos"],
    schedules: [1, 4, 5],
  },
  {
    id: 10,
    code: "20010",
    name: "Nodo AED 1",
    phone: "917945449",
    agents: 10,
    priority: "Baja",
    typification: false,
    channels: ["phone", "chat"],
    strategy: "Balanceada",
    chatStrategy: "Rotativa (por turnos)",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Oscar Bello", "Oscar Fernandez", "Rafael"],
    services: ["Atención general", "Soporte técnico", "Consultas facturación"],
  },
  {
    id: 11,
    code: "20011",
    name: "Online Support",
    phone: "918371548",
    agents: 13,
    priority: "Máxima",
    typification: false,
    channels: ["phone", "chat", "email"],
    strategy: "Balanceada",
    chatStrategy: "Menos chats activos",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis", "Rafael"],
    labels: [3, 6],
    templates: [1, 2, 3, 4, 5, 11],
    services: ["Soporte técnico", "Soporte web"],
    schedules: [1, 2, 3],
  },
  {
    id: 12,
    code: "20012",
    name: "Reclamaciones",
    phone: "918371548",
    agents: 15,
    priority: "Alta",
    typification: true,
    channels: ["phone", "chat"],
    strategy: "Balanceada",
    chatStrategy: "Rotativa (por turnos)",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis", "Rafael", "Angel personal", "Miguel Palacios 2"],
    labels: [4, 10],
    templates: [7, 8, 10],
    services: ["Reclamaciones", "Atención general"],
    schedules: [1, 2],
  },
  {
    id: 13,
    code: "20013",
    name: "Soporte Taller",
    phone: "917945449",
    agents: 13,
    priority: "Máxima",
    typification: false,
    channels: ["phone", "chat"],
    strategy: "Lineal",
    chatStrategy: "Menos chats activos",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Miguel Palacios 3", "Oscar Bello", "Oscar Fernandez", "Oscar Quobis", "Rafael"],
    services: ["Soporte taller", "Averías"],
  },
  {
    id: 14,
    code: "20014",
    name: "Telemarketing",
    phone: "918371548",
    agents: 11,
    priority: "Baja",
    typification: false,
    channels: ["phone"],
    strategy: "Balanceada",
    assignedAgents: ["Agente AED 1", "Agente AED 2", "Agente demo", "Agente Jose", "Jose Barcala", "Mario Perez", "Marta Recio", "Miguel Palacios", "Oscar Bello", "Oscar Fernandez", "Rafael"],
    services: ["Telemarketing VUI"],
  },
];